### ISSUE TITLE
Icons for you!

### ISSUE THREAD

**Issue by IvoDerksen** [robertklep/name.klep.sonoff#1]
Hey Robert,

I was talking to a colleague about these devices, I've decided to make an icon pack for the app.
So here you go!

[Sonoff icons.zip](https://github.com/robertklep/name.klep.sonoff/files/1535715/Sonoff.icons.zip)

**Comment by robertklep** [comment]
Absolutely brilliant!

If I may be so bold: there's an icon missing for the [Sonoff Basic](http://sonoff.itead.cc/en/products/sonoff/sonoff-basic), which is similar to the Sonoff RF, but without the "RF" part.

I'm also planning support for the [RF Bridge](http://sonoff.itead.cc/en/products/appliances/sonoff-rf-bridge-433), but I'll have to order one first.

**Comment by IvoDerksen** [comment]
Well here you go!

[basic-rf.zip](https://github.com/robertklep/name.klep.sonoff/files/1537307/basic-rf.zip)

**Comment by IvoDerksen** [comment]
Good luck on finishing the integration, and the long wait! I'm waiting for my $5 sonoff basic too :)
