### ISSUE TITLE
Support for touch devices with tasmota firmware..? 

### ISSUE THREAD

**Issue by BPC83** [robertklep/name.klep.sonoff#10]
Hi, will sonoff touch devices with tasmota firmware be supported in the future.?

**Comment by robertklep** [comment]
You can probably already use the app with Touch devices (if you have to pick a device type, choose "Sonoff Basic").

However, for now, only one button/relay is supported, so a Touch device with multiple buttons won't be (fully) supported yet (I'm working on support for devices with multiple relays as we speak).

**Comment by robertklep** [comment]
@BPC83 if you set the module type for the 2-button device to "Dual" (in the Tasmota configuration), you should be able to add it as a Dual device to Homey.

If that works, I can easily add new drivers for each different Touch device.

**Comment by robertklep** [comment]
Each driver has a fixed list of modules it will support, so it will only allow devices configured as one of those modules be paired (the "Sonoff T1 2CH" module isn't supported by any driver yet).

It's weird though that the "Dual" module doesn't work. Could you try setting it to the "Sonoff Dual R2" module and try again?

**Comment by BPC83** [comment]
@robertklep  in tasmota (web) it is working, but not possible to add to homey, with the one dual device there is listed in homey.

**Comment by robertklep** [comment]
I assume it doesn't show up when you try to pair it? Are you power-cycling device while Homey is waiting for it to show up?

**Comment by BPC83** [comment]
no it does not show in homey, it is just waiting fore it.. after 10 min, I canceled it.. 
yes, I am rebooting the sonoff device from the tasmota web interface..

**Comment by robertklep** [comment]
Strange. After the device has rebooted, it sends its status info to the MQTT broker, which is what the Sonoff app is waiting for. I don't quite understand why it's not being picked up (especially weird since it does work when you configure it as a 4CH device).

**Comment by BPC83** [comment]
I tried it one more time, and now it is actually working, with tasmota as Dual R2 and added to homey as dual.. and both switched in homey works...

**Comment by robertklep** [comment]
Okay cool (and strange ;)).

That means that I can just copy the Dual driver for the 2CH Touch device (and the Basic driver for the 1CH, and create a new driver for the 3CH). Should be simple enough :)

**Comment by BPC83** [comment]
yes... that sound simple... my testings is with the UK version... I have also a EU version but I thing that will be the same.. but will test it later... the 3ch is only available in US and UK versions, the EU versions have to be smaller to fit in to an euro wall box, but I think the software factions will be the same for all versions... but... iam looking to buy an 3ch US version, as I need 3 buttons beside my bed... If I can find a wall box for an US version on ebay, in Denmark we are special, we have very small switches, and outlets.. only 50x50mm for a switch...

**Comment by BPC83** [comment]
Bad news........ when tasmota is set to dual R2 the buttons on the device does not work... changed it back to 4ch and buttons working again....

**Comment by robertklep** [comment]
Perhaps the Dual is "special" for Tasmota. I will release a beta version with support for all three T1 devices, hopefully those work as expected.

**Comment by robertklep** [comment]
Just submitted v4.0.4 (beta) to the Homey app store, with support for T1 and POW devices (#6)

**Comment by robertklep** [comment]
v4.0.4 was just published.

**Comment by BPC83** [comment]
done a quick test, the 1ch works fint...

2ch. adding to homey, looks fine, it is found, added to the list, and when I click on the sliders icon, there is a message, "waiting for connection" and after some time, (20-30 sek after adding) the main icon in homey changes to the no connection icon... 
i have not time fore more testing today, but will return testing tomorrow

**Comment by robertklep** [comment]
Thanks for testing, sounds like the app might be crashing. I just realized that I could try and use my Dual as if it's a T1 2CH, so will run some tests as well.

**Comment by robertklep** [comment]
No, running the Dual as if it was a T1 2CH works just fine. That doesn't necessarily mean it's supposed to with with a _real_ T1 2CH, but at least there isn't an obvious bug in the code.

**Comment by robertklep** [comment]
Closing as T1 1/2/3CH devices are now supported.
