### ISSUE TITLE
Sonoff TH16 No new devices

### ISSUE THREAD

**Issue by StraDijk** [robertklep/name.klep.sonoff#12]
I'am not able to add the TH16 to Homey. 

When i change module type to POW the device shows in Homey.

INFO1:
{"Module":"Sonoff TH","Version":"5.14.0","FallbackTopic":"DVES_372B33","GroupTopic":"sonoffs"}

**Comment by robertklep** [comment]
Weird, I have an TH10, which uses the same module, and that gets picked without problems:
```
{"Module":"Sonoff TH","Version":"5.12.0","FallbackTopic":"DVES_0DE76C","GroupTopic":"sonoffs"}
```

Do make sure that if you have paired the device previously (as a POW, for instance), you first need to remove the old device before you pair it again as a new type. The app uses the MAC address for the module as unique identifier, and that value doesn't change if you change the Tasmota module type (so the app thinks it's already paired).

**Comment by StraDijk** [comment]
Paired device was removed, before adding it again.

After several homey reboots, i was able to add the device again.
