### ISSUE TITLE
Little help on MQTT

### ISSUE THREAD

**Issue by torstengram** [robertklep/name.klep.sonoff#17]
Hi,
i have 3 devices two S20 and a 4ch device. From their webinterface they run OK toggling the channels, from within homey the tw S0 and ch1 on the 4ch are syncronised.
What exactly do i need to change in order to switch them seperate? is it the topic?

**Comment by robertklep** [comment]
Yes exactly, each device should be given a unique topic :)

**Comment by torstengram** [comment]
perfect, now the devices are working independently. Thanks a lot !
