### ISSUE TITLE
Recommend trying --data-ascii first

### ISSUE THREAD

**Issue by MrZANE42** [robertklep/name.klep.sonoff#2]
Hi
I've provisioned quite a few Sonoff devices now and all of the worked when using --data-ascii in the curl command line, and the ones I accidentally tried with --data-binary failed.
So a suggestion would be to changed the example to use --data-ascii and offer --data-binary as an alternative instead of the other way around.

Keep up the good work, the devices works perfectly with Homey and I'm glad that I soon can get rid of the power-hungry eWeLink app from my phone

**Comment by robertklep** [comment]
Thanks, I will change it :)

I'm working on a setup page that can be run from inside the Homey application, instead of having to use curl from a command line shell.

Just out of curiosity: what types of devices have you (successfully) provisioned?

**Comment by MrZANE42** [comment]
Hi again.
We've been in contact before on the athom apps page for your App.
You find me there as Jimmy Pedersen and I've posted the ones I've tried there (Including one today).
If you want me to post model info somewhere else just tell me.

**Comment by robertklep** [comment]
@MrZANE42 thanks, the forum post is sufficient :) I'll close this issue, when the next update gets pushed the changes will be in it.
