### ISSUE TITLE
rf bridge code cannot be entered in homey 2.0

### ISSUE THREAD

**Issue by Abduljalilabbasi** [robertklep/name.klep.sonoff#24]
RF bridge is running and sniffing is ok, i can see rf codes

in the flow code is shown blank, and i cannot enter it manually.

regards

**Comment by robertklep** [comment]
You have to add a condition ("AND") card to match the code:

![image](https://user-images.githubusercontent.com/1190916/54879715-82bdec80-4e3c-11e9-8a75-ff02ad3868a8.png)

(from left to right: "RF code received", "[Code] is exactly ...", "Make a notification")
