### ISSUE TITLE
Sonoff Basic R3 original firmware

### ISSUE THREAD

**Issue by Atomicprogress** [robertklep/name.klep.sonoff#27]
Hi, sonoff basic R3 are now compatible with your app in LAN mode?
is it possible to make these new sonoff R3 work with an update of your plugin? or is there no hope?
thanks

**Comment by robertklep** [comment]
No, the app doesn't support LAN mode, and I have mostly stopped developing for Homey so it's not likely that I will implement support for it, I'm afraid.
