### ISSUE TITLE
Sonof SV with Tasmota and PulseTimer

### ISSUE THREAD

**Issue by shaarkys** [robertklep/name.klep.sonoff#33]
Hi,
Sonof SV (https://www.itead.cc/wiki/Sonoff_SV) is not among offered devices, so I have added it as "Generic" / Tasmota device, device type as Basic. However I'm using Sonof SV as garage opener, so I had to set PulseTimer. This is where the problem arise - as the Sonof switch is on only for aprox. 2 sec, Homey is not reflecting status correctly and not immidiately.
When I however setup MQTT Dashboard - IoT and Node-RED controller on my Android phone, using following parameters, it shows it's status perfectly. Anything you can implement eventually ? 

It could be the case I'm doing something incorrectly naturally (not expert at all and MQTT is something I'm totally not familiar with), then I'm sorry for this "issue/enhancement suggestion"

Thank you.

**Subscribe topic :** stat/sonoff/POWER 
**Publish topic :** cmnd/sonoff/power

**Comment by robertklep** [comment]
I'm afraid I'm not planning to do any development on this app for the foreseeable future. Perhaps you can create a workaround using the MQTT Client app and a virtual device.
