### ISSUE TITLE
Add support of  Sonoff T4 EU 1C or at least support it as T1 in app

### ISSUE THREAD

**Issue by rgzvld** [robertklep/name.klep.sonoff#35]
Please add support of  Sonoff T4 EU 1C or at least support it as T1 in app. I'm able to connect T4 with homey as sonoff "basic", but not T1. While I'm trying to connect t4 as t1 in app, after t4 device restart (as per instruction), I get the following error message: no new devices found. But on case if I configure t4 as "basic" it works as well. Please fix or advice, thanks.
![73ECF7AC-E7DD-4F48-91D9-E3E1C513C21E](https://user-images.githubusercontent.com/13552621/68868587-79053400-0700-11ea-8a38-992e1423f2cc.jpeg)

**Comment by robertklep** [comment]
You need to configure the device as either a Basic or a T1 in the Tasmota configuration first.

**Comment by rgzvld** [comment]
oh... I've changed it to T1 1CH, it's successfully found but now please see the screenshot 
![2FC589C1-D268-4031-9B1B-73C68A0BF66C](https://user-images.githubusercontent.com/13552621/68872617-ff247900-0706-11ea-96dd-a35ddeedeeaf.jpeg)

**Comment by robertklep** [comment]
That's not an error that the Sonoff app generates. Perhaps you could open https://developer.athom.com/tools/devices, find the device, and see if there's anything being shown that looks like an error message?

**Comment by rgzvld** [comment]
It's a little bit strange, I've just rebooted the homey, and now it works as expected. Thank you and sorry for disturbing

**Comment by robertklep** [comment]
No problem, good to hear you solved it 😁
