### ISSUE TITLE
class type

### ISSUE THREAD

**Issue by CMYDmark** [robertklep/name.klep.sonoff#44]
Hello, is it possible to choose/change a class type for the Sonoff ZBmini device so that it is not recognized as a light but something else? The issue is that it currently toggles along when the command "turn off all lichts", but there is no light connected to the device, but rather a computer that shouldn't toggle with the lights.

**Comment by robertklep** [comment]
Hi! This isn't the correct repository to ask, see [the app page](https://homey.app/en-nl/app/tech.sonoff/SONOFF-Zigbee/) on how to contact the app developer.

That said, for some classes of devices, you can change the type of device that is connected to it. You can do so in the mobile app by selecting the device (by long-pressing on it) and then press the gear icon in the top right corner. If it's possible to change the "connected device type", you'll see a "Plugged In" setting.
