### ISSUE TITLE
Sonoff T1 EU suited for roller shutter?

### ISSUE THREAD

**Issue by HeHaHu** [robertklep/name.klep.sonoff#7]
I don’t know how I ended up on this website. And I really don’t know how to behave here and what to expect. Can I ask something? What do I need to do? I can put done my story?

In the past I bought myself a Sonoff Motor Clockwise/Anticlockwise Running WiFi Wireless Switch Model: IM160601001 control, in a case (see picture), a roller shutter. I was perfectly happy with this product and was willing to buy more for my other shutters. But then found out it was retired. Since then only 1 shutter is controlled by my smartphone.

Now I read about the Sonoff T1 EU: 2 Gang WiFi RF Smart Wall Touch Light Switch. This might be the solution to my problem. In my opinion I could use the 2-gang version to replace the Motor Clockwise/Anticlockwise. There is only 1 catch. When using switch 1 the power to switch 2 should automatically be cut off. And when using switch 2 the power to switch 1 should automatically be cut off as well of course. An option to cut off the power for switch 1 and 2 at the same time would be great as well. In that case the shutter can be stopped at any position.

Itead advised me to use "scene", but you need active internet for that. In case of operating the shutter manually by using the switch without internet connection there would be active power on both switches. The shutter motor simultaneously would have power on "closing" and "opening" and would definitely not like that I think ;-).

To my opinion the best solution would be a firmware solution. But how to accomplish that ;-)?

![motor clockwise-anticlockwise](https://user-images.githubusercontent.com/29672705/36936168-9c1eb814-1f01-11e8-9ce7-e2fdd624a209.jpg)

**Comment by robertklep** [comment]
Sorry for the late reply.

The	[Sonoff 4CH Pro](https://www.itead.cc/smart-home/sonoff-4ch-pro.html) device has an "interlock" operating mode, which suggests that it _might_ be possible to do what you want. However, I don't have such a device, so I can't be certain it will work exactly how you want it to work.

I don't see any other devices in the current Sonoff range that you can use out-of-the-box (for instance, the Sonoff Dual device has two relays, but they are completely independent), and a commonly used alternative firmware, Sonoff-Tasmota, also doesn't seem to have a locking mode feature.

**Comment by HeHaHu** [comment]
Hello,

 

Thank you for your reply.

 

Yes, the  <https://www.itead.cc/smart-home/sonoff-4ch-pro.html> Sonoff 4CH Pro would suit my demands. It has an interlock mode and that is what I need. The only thing is that it is a hideous device. I would need one for every roller shutter and that wouldn’t look nice in my house. And the fact that I would need 1 for every shutter makes it quite expensive as well. I read that it would be possible to connect 2 motors to this 4CH Pro. But would 4 motors be possible as well you think, see attachment? 

I own just 1   <https://www.itead.cc/motor-reversing-wifi-wireless-switch.html> Motor Clockwise/ Anticlockwise. I have used it for 1 shutter and it works great. If it wasn’t made obsolete I would have, after I had tested the 1 I have, bought many more. But the most ideal solution would be the Sonoff T1 EU: 2 Gang <https://www.itead.cc/sonoff-t1-eu.html> ………….. that is, if it had an interlock mode. From a cosmetic point of view it looks the best of all Sonoff devices. The question is, would it be possible to “add” this to the features of this Sonoff? 

 

Regards,

 

Henry 

HeHaHu

Internet: www.hehahu.nl

Email:  <mailto:henry@hehahu.nl> henry@hehahu.nl

Skype: henry.hehahu

Cell: 06-16195485

 <http://www.hehahu.nl/index.php?option=com_phocaguestbook&view=phocaguestbook&id=1&Itemid=6> My guestbook

 

Van: Robert Klep [mailto:notifications@github.com] 
Verzonden: maandag 19 maart 2018 13:01
Aan: robertklep/name.klep.sonoff <name.klep.sonoff@noreply.github.com>
CC: HeHaHu <henry@hehahu.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [robertklep/name.klep.sonoff] Sonoff T1 EU suited for roller shutter? (#7)

 

Sorry for the late reply.

The Sonoff 4CH Pro <https://www.itead.cc/smart-home/sonoff-4ch-pro.html>  device has an "interlock" operating mode, which suggests that it might be possible to do what you want. However, I don't have such a device, so I can't be certain it will work exactly how you want it to work.

I don't see any other devices in the current Sonoff range that you can use out-of-the-box (for instance, the Sonoff Dual device has two relays, but they are completely independent), and a commonly used alternative firmware, Sonoff-Tasmota, also doesn't seem to have a locking mode feature.

**Comment by robertklep** [comment]
Ik zie dat je Nederlands bent :)

Voor zover ik kan zien heb je voor één motor 2 kanalen nodig: één voor omhoog en één voor naar beneden. Dus met een 4CH device kan je maximaal 2 motoren bedienen.

De 2-kanaals apparaten (de Dual en de T1, o.a.) hebben geen interlocking dus die vallen _met de standaard firmware_ af.

Misschien is het toch mogelijk met de Sonoff-Tasmota firmware (zie [deze thread](https://github.com/arendst/Sonoff-Tasmota/issues/820), waar iemand iets vergelijkbaars wil als jij), maar dat zou een kwestie van uitproberen zijn om te zien of het wel echt werkt.

Mocht je de stap willen wagen en een T1 aanschaffen dan kunnen we wel afspreken dat ik die firmware voor je op het apparaat installeer. Ik woon namelijk ook in Den Bosch :)

**Comment by HeHaHu** [comment]
Dat meen je niet hahaha. Ik woon inderdaad in ’s-Hertogenbosch. Jouw achternaam is Klep, klopt dat? Er komt bij mij een naam naar boven, maar weet niet waarom; Edwin Klep. Zegt jou dat iets? En ook Koopvaardijstraat komt er in me op.

 

Dat klopt, 1 voor omhoog en 1 voor naar beneden. De motor van het rolluik heeft zelf een automatische, instelbare, stop. Daarom was die, ondanks dat heel veel mensen erover zanikten dat er geen stop op zat, Motor Clockwise/ Anticlockwise voor mij perfect. Ik heb ook een Towitek <https://www.conrad.nl/nl/4-kanaals-radiografisch-schakelsysteem-towitek-twt2028-191401.html?WT.mc_id=vergelijkers:vergelijk:feed:191401&utm_campaign=d6aad21c-ddc4-440e-8ee7-f5f9a6512314&utm_medium=vergelijkers&utm_source=vergelijk&utm_term=191401>  en dat ziet er voor mij als leek qua aansluitingen hetzelfde uit. Daar kan ik 4 rolluiken mee bedienen. Er zitten volgens mij 4 relais op en die hebben elk een aansluiting met NO en NC. Als ik daartussen wissel gaat het rolluik open en dicht. Is dat bij die  <https://www.itead.cc/smart-home/sonoff-4ch-pro.html> Sonoff 4CH Pro niet hetzelfde?

 

Inderdaad die 2 hebben geen interlock. In theorie zou de T1 te gebruiken zijn, maar in de praktijk betekent dat dat eerst 1 kanaal uitgeschakeld dient te worden voor het ander kanaal ingeschakeld wordt anders wordt de motor niet zo blij vermoed ik.

 

Dat, die thread, lijkt me inderdaad wat ik bedoel. Vooruitlopend op alles had ik al een T1 besteld en ook vorige week geleverd gekregen. Dat ding beschouw ik als een proefobject als iemand iets wil proberen. Nou heb ik hem afgelopen weekend meegenomen naar Duitsland en hem daar laten liggen omdat ik dacht hem voorlopig toch niet nodig te hebben. Maar er is hoop, aankomend weekend ben ik daar weer en ik kan hem zondag mee terug brengen. Het mooiste zou zijn dat ik het zelf leer om dat te doen. Ik heb er namelijk nogal wat nodig.

 

Ik hoor graag weer van je.

 

Groet,

 

Henry 

HeHaHu

Internet: www.hehahu.nl

Email:  <mailto:henry@hehahu.nl> henry@hehahu.nl

Skype: henry.hehahu

GSM: 06-16195485

 <http://www.hehahu.nl/index.php?option=com_phocaguestbook&view=phocaguestbook&id=1&Itemid=6> Mijn gastenboek

 

Van: Robert Klep [mailto:notifications@github.com] 
Verzonden: maandag 19 maart 2018 14:18
Aan: robertklep/name.klep.sonoff <name.klep.sonoff@noreply.github.com>
CC: HeHaHu <henry@hehahu.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [robertklep/name.klep.sonoff] Sonoff T1 EU suited for roller shutter? (#7)

 

Ik zie dat je Nederlands bent :)

Voor zover ik kan zien heb je voor één motor 2 kanalen nodig: één voor omhoog en één voor naar beneden. Dus met een 4CH device kan je maximaal 2 motoren bedienen.

De 2-kanaals apparaten (de Dual en de T1, o.a.) hebben geen interlocking dus die vallen met de standaard firmware af.

Misschien is het toch mogelijk met de Sonoff-Tasmota firmware (zie deze thread <https://github.com/arendst/Sonoff-Tasmota/issues/820> , waar iemand iets vergelijkbaars wil als jij), maar dat zou een kwestie van uitproberen zijn om te zien of het wel echt werkt.

Mocht je de stap willen wagen en een T1 aanschaffen dan kunnen we wel afspreken dat ik die firmware voor je op het apparaat installeer. Ik woon namelijk ook in Den Bosch :)
