### ISSUE TITLE
Not work with Tasmota MQTT

### ISSUE THREAD

**Issue by SadhuRus** [robertklep/name.klep.sonoff#9]
In Homey, when I try add sonof device with this params:

MQTT broker hostname/IP: 192.168.1.233 (Enter ip-adrees with Tasmota/Sonoff Relay)
MQTT broker port: 1883

I have error: "MQTT connection unsuccessful."
What is problem? 

In Sonoff Basic Module Configuration MQTT was ON.

**Comment by robertklep** [comment]
Is 192.168.1.233 the address of the MQTT broker, or of the Sonoff device? It should be the broker address (the Sonoff devices don't have a built-in MQTT broker, only a client).

**Comment by SadhuRus** [comment]
Yes.. Its address only Sonof device. 
While it is unclear how to make a broker and how the technology works mqtt. I'll try to understand

**Comment by robertklep** [comment]
My apologies is things aren't really very clearly documented, it does assume an amount of "pre-knowledge" on what all the terms mean and how to get it working.

The MQTT broker is like a go-between between the Sonoff device(s) and the Homey app. The device sends messages to the broker, and the Homey app listens for new messages.

The easiest method to get it up and running is to run the MQTT broker on Homey itself, using the [MQTT Broker](https://apps.athom.com/app/nl.scanno.mqttbroker) app. It's easy to set up, doesn't take a lot of resources, and I use it myself.

Once you have it up and running, you set up both the device and the Homey app so they point to the broker running on Homey (using Homey's IP-address in your internal network).

**Comment by SadhuRus** [comment]
Installed and configured as you said. Everything worked! Cool! Thank you so much
